### ISSUE TITLE
Race Cars Start Position

### ISSUE THREAD

**Issue by ever-Lord** [explosivegaming/factorio-olympics#57]
**Feature overview**
Name: Randomizing start position
I have participed in like 20 races and i always started in last position

Can we randomize that ? 
Or find a way to order it, based on bets lap times for example ?
Or have a large Start/Finish line so all players are in a line ? (Bonus : players have to run to their car at the beginning, LeMans Style)

**Comment by Hornwitser** [comment]
The order is based on the order that players connected and loaded into the server.  Which is kind of unfair.

**Comment by Cooldude2606** [comment]
Pr has been merged which implements random starting position for racers, closing this issue.

**Comment by ever-Lord** [comment]
i'm not sure the patch is working, since one's car is placed when he joins. may be my impression is wrong, but it feels cars are place on grid when player joins. thats what i saw on jd's stream : https://www.twitch.tv/videos/726056590?t=00h49m25s

**Comment by Cooldude2606** [comment]
Yes the cars are placed on join, that is so there are the correct number of cars. Before the behaviour was to assign the cars as they were made, the new behaviour adds them to an array as they are made and then randomly selects which one a player gets once all players have joined.
